namespace Otter.Business.Dtos
{
    public class FannavaranExcelDto
    {
        public string PersonKind { get; set; }
        public string PersonName { get; set; }
        public string PersonLName { get; set; }
        public string IsIranian { get; set; }
        public string Nationality { get; set; }
        public string CodeMelli { get; set; }
        public string UnIranianCode { get; set; }
        public string PersonJens { get; set; }
        public string BirthYear { get; set; }
        public string GElhNo { get; set; }
        public string BirthMonth { get; set; }
        public string BirthDay { get; set; }
        public string IdentityNo { get; set; }
        public string SodurPlace { get; set; }
        public string FatherName { get; set; }
        public string Economic { get; set; }
        public string CompanyCode { get; set; }
        public string SabtNo { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string CodePosti { get; set; }
        public string PersonAddress { get; set; }
        public string PayerPersonKind { get; set; }
        public string PayerPersonName { get; set; }
        public string PayerPersonLName { get; set; }
        public string PayerIsIranian { get; set; }
        public string PayerNationality { get; set; }
        public string PayerCodeMelli { get; set; }
        public string PayerUnIranianCode { get; set; }
        public string PayerPersonJens { get; set; }
        public string PayerBirthYear { get; set; }
        public string PayerBirthMonth { get; set; }
        public string PayerBirthDay { get; set; }
        public string PayerIdentityNo { get; set; }
        public string PayerSodurPlace { get; set; }
        public string PayerFatherName { get; set; }
        public string PayerEconomic { get; set; }
        public string PayerCompanyCode { get; set; }
        public string PayerSabtNo { get; set; }
        public string PayerMobile { get; set; }
        public string PayerTel { get; set; }
        public string PayerCodePosti { get; set; }
        public string PayerPersonAddress { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string LastBimeCompany { get; set; }
        public string InternalOldBId { get; set; }
        public string ExtendedPolicyId { get; set; }
        public string ExtendedBNNo { get; set; }
        public string TakhfifPercent { get; set; }
        public string FishNo { get; set; }
        public string FishDate { get; set; }
        public string Bank { get; set; }
        public string BankBranchNumber { get; set; }
        public string BankBranch { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string SerialNo { get; set; }
        public string ManufactureYear { get; set; }
        public string PartOneSarmaye { get; set; }
        public string NerkhPartOne { get; set; }
        public string PartOneHB { get; set; }
        public string PartTwoSarmaye { get; set; }
        public string FranshizDarsadPartTwo { get; set; }
        public string MinFranshizPartTwo { get; set; }
        public string NerkhPartTwo { get; set; }
        public string PartTwoHB { get; set; }
        public string FillPayerFromBimegozar { get; set; }
    }
}